name: "CI"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  show-github-context:
    runs-on: ubuntu-20.04
    env:
      GITHUB_CONTEXT: ${{ toJson(github) }}
    steps:
      - run: echo $GITHUB_CONTEXT

  pr:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: 14
      - name: update
        run: sbt -batch update
      - name: scalafmt
        run: sbt -batch scalafmtCheckAll
      - name: compile
        run: sbt -batch compile
      - name: doc
        run: sbt -batch doc
      - name: test
        run: sbt -batch test
