name: "CI"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  show-github-context:
    runs-on: ubuntu-20.04
    env:
      GITHUB_CONTEXT: ${{ toJson(github) }}
    steps:
      - run: echo $GITHUB_CONTEXT

  scalafmt:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: 14
      - name: scalafmt
        run: sbt -batch scalafmtCheckAll

  docs:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        scala: ["2.12.12", "2.13.5"]
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: 14
      - name: doc
        run: sbt -batch "++ ${{ matrix.scala }} doc"
      - name: mdoc
        run: sbt -batch "++ ${{ matrix.scala }} mdoc"

  tests:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        scala: [ "2.12.12", "2.13.5" ]
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: 14
      - name: update
        run: sbt -batch "++ ${{ matrix.scala }} update"
      - name: compile
        run: sbt -batch "++ ${{ matrix.scala }} compile"
      - name: test-compile
        run: sbt -batch "++ ${{ matrix.scala }} test:compile"
      - name: test
        run: sbt -batch coverage "++ ${{ matrix.scala }} test"
