name: "Release"

on:
  repository_dispatch:
    types: release

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup Credentials
      env:
        GPG_SECRET_B64: ${{ secrets.GPG_SECRET_B64 }}
        SBT_SONATYPE_B64: ${{ secrets.SBT_SONATYPE_B64 }}
      run: ./.github/scripts/secrets.sh
    - uses: olafurpg/setup-scala@v10
    - name: Git setup
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
    - name: Update
      run: sbt -batch update
    - name: Compile
      run: sbt -batch compile
    - name: Release
      run: sbt -batch "release with-defaults"
